[workspace]
members = ["lexer", "repl", "parser", "interpreter", "compiler"]
default-members = ["repl"]
resolver = "2"

[workspace.dependencies]
lexer = { path = "./lexer" }
parser = { path = "./parser" }
interpreter = { path = "./interpreter" }
compiler = { path = "./compiler" }
